#!/usr/bin/env bash
# this script installs and configure HAproxy on the lb-01 server.
# The load balancer is configured according to the requirements below:
#+ HAproxy must send traffic to web-01 and web-02
#+ Distribute requests using a roundrobin algorithm
#+ HAproxy must be manageable via an init script

# update packages and install haproxy
sudo apt udate
sudo apt install -y haproxy=2.0\*

# permission access
sudo chmod 700 /etc/haproxy/haproxy.cfg

# add a new load balancer configuration
printf %s "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server web-01 44.200.187.123:80 check
   server web-02 54.224.16.135:80 check
" >> /etc/haproxy/haproxy.cfg

# restart haproxy
sudo services haproxy restart
