#!/usr/bin/env bash
# this script installs and configure HAproxy on the lb-01 server.
# The load balancer is configured according to the requirements below:
#+ HAproxy must send traffic to web-01 and web-02
#+ Distribute requests using a roundrobin algorithm
#+ HAproxy must be manageable via an init script

balancer="\
frontend http_front
    bind *:80
    mode http
    default_backend http_back
    
backend http_back
    balance roundrobin
    server web-01 44.200.187.123:80 check
    server web-02 54.224.16.135:80 check
"
# Update packages
apt-get -y update

# Add HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

#configure haproxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
