#!/usr/bin/env bash
# this script installs and configure HAproxy on the lb-01 server.
# The load balancer is configured according to the requirements below:
#+ HAproxy must send traffic to web-01 and web-02
#+ Distribute requests using a roundrobin algorithm
#+ HAproxy must be manageable via an init script

# update packages and install haproxy
sudo apt update
sudo apt install -y haproxy=2.0\*

# add a new load balancer configuration
printf %s "\
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server 42562-web-01 44.200.187.123:80 check
    server 42562-web-02 54.224.16.135:80 check
" >> /etc/haproxy/haproxy.cfg

# restart haproxy
sudo service haproxy restart
