#!/usr/bin/env bash
# bash script to automate the fix on a buggy ubuntu nginx server installation

sudo apt update
sudo apt install -y nginx

printf %s "Server {
    listen 80 default_server;
    root /var/www/html
    index index.html
}" > /etc/nginx/sites-available/default

sudo service restart nginx
