#!/usr/bin/env bash
# run command as another user while taking a single argument

if [ $# -gt 2 ]
then 
  echo "this program accepts only one argument!"
elif [ $# -eq 1]
then
  echo "supply the user argument"
else
  sudo -u "$1" -c whoami
fi
